In [1]:
import numpy as np
import pandas as pd

filename_train  = '/home/sombit/Machine-Learning19/Assignment2/data2_19.csv'

filename_tesst  = '/home/sombit/Machine-Learning19/Assignment2/test2_19.csv'


In [2]:
def prepare_dataframe(df):
    temp = []
    for j in range(len(df)):
        string = ""
        for i in range(len(df.iloc[j,:])):
            string += str(df.iloc[j,i])
        temp.append([int(char) for char in string.split(',')])

    df = pd.DataFrame(temp, columns = df.columns.values[0].split(","))

    return df

In [3]:
def pos_prob(data):
    pos = 0
    neg = 0
    for i in range (len(data)):
        if(data[i][0]==0) :
            pos = pos+1
        else : 
            neg = neg+1
    # print ("pos",pos," neg ",neg)
    return pos,neg


In [4]:
def temp(data):
    table_a = np.zeros((6,5))
    table_b = np.zeros((6,5))
    
    for i in range(len(data)):
        if(data[i][0]==1):
            for j in range(len(data[0])-1):
                # print ("j",j)
                table_a[j][data[i][j+1]-1] =table_a[j][data[i][j+1]-1]+1
        else:
            for j in range(len(data[0])-1):
                # print ("j",j)
                table_b[j][data[i][j+1]-1] =table_b[j][data[i][j+1]-1]+1 
    print(table_a)
    print(table_b) 
    return table_a,table_b

In [15]:
def main ():
    data = pd.read_csv(filename_train) 
    data = prepare_dataframe(data)
    data =pd.DataFrame(data).to_numpy()
    test = pd.read_csv(filename_tesst) 
    test = prepare_dataframe(test)
    test =pd.DataFrame(test).to_numpy()
    # data = data[:10]
    pos,neg = pos_prob(data)
    # print ( "pos ",pos )
    # temp(data)
    table_a,table_b = temp(data)
    predict = []
    for i in range (len(test)):
        val1 = 1.0
        val0 = 1.0
        for  j in range (len(test[0])-1 ):
            print (test[i][j+1] ,j," ",table_b[j][test[i][j+1]-1] ,",table_a[j][test[i][j+1]-1]")
            val1 = val1*(table_a[j][test[i][j+1]-1] +1)/(pos+5)
            val0 = val0*(table_b[j][test[i][j+1]-1] +1)/(neg+5)
        val0 = val0 * neg
        val1 = val1 * pos
#         print ("i ",i+1 , "val0 ",val0 , "val1" ,val1)
        if(val1 > val0 ) :
            predict.append(1)
#             print("true ")
        else: 
            predict.append(0)
            print ("false")
    correct =0
    total = 0
    for i in range (len(predict) ):
        total = total +1
        if(predict[i]==test[i][0]):
            correct = correct+1
    print(correct/total)        # cout << 0 << endl;

main()

[[ 0.  0.  7. 18. 45.]
 [13. 23. 22.  8.  4.]
 [ 2.  9. 25. 24. 10.]
 [ 1.  1. 24. 30. 14.]
 [ 1.  8. 11. 30. 20.]
 [ 0.  0.  5. 28. 37.]]
[[ 1.  0. 16. 25. 17.]
 [15. 14. 18. 10.  2.]
 [ 4.  7. 34.  9.  5.]
 [ 0.  5. 24. 21.  9.]
 [ 5.  9. 15. 22.  8.]
 [ 1.  1. 16. 24. 17.]]
5 0   17.0 ,table_a[j][test[i][j+1]-1]
1 1   15.0 ,table_a[j][test[i][j+1]-1]
4 2   9.0 ,table_a[j][test[i][j+1]-1]
4 3   21.0 ,table_a[j][test[i][j+1]-1]
4 4   22.0 ,table_a[j][test[i][j+1]-1]
5 5   17.0 ,table_a[j][test[i][j+1]-1]
5 0   17.0 ,table_a[j][test[i][j+1]-1]
2 1   14.0 ,table_a[j][test[i][j+1]-1]
2 2   7.0 ,table_a[j][test[i][j+1]-1]
4 3   21.0 ,table_a[j][test[i][j+1]-1]
4 4   22.0 ,table_a[j][test[i][j+1]-1]
5 5   17.0 ,table_a[j][test[i][j+1]-1]
5 0   17.0 ,table_a[j][test[i][j+1]-1]
3 1   18.0 ,table_a[j][test[i][j+1]-1]
5 2   5.0 ,table_a[j][test[i][j+1]-1]
4 3   21.0 ,table_a[j][test[i][j+1]-1]
5 4   8.0 ,table_a[j][test[i][j+1]-1]
5 5   17.0 ,table_a[j][test[i][j+1]-1]
3 0   16.0 ,table_a[j][t